version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres'
    restart: always
    volumes:
      - ./postgres-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: nestjs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080